### ISSUE TITLE
unable to run releases

### ISSUE THREAD

**Issue by weswalla** [kaichaosun/ad4m-host#18]
When I download the release and try to run it, I get the following error (on both linux and mac):
```
wesley@wesley-ubuntu:~/perspect3vism$ ./ad4m-linux-x64 init
(node:34860) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `ad4m-linux-x64 --trace-warnings ...` to show where the warning was created)
```

**Comment by kaichaosun** [comment]
Hi @weswalla this is a warning and should not affect use.
I was looking to resolve the warning, but haven't got any solution yet.

**Comment by weswalla** [comment]
ah thx!
